import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Utils/Navbar";
import Footer from "./Components/Utils/Footer";
import State from "@/app/Context/State";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Marginal Classes - The Commerce Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <State>
          <Navbar />
          {children}
          <Footer />
        </State>
      </body>
    </html>
  );
}
